twig:
    file_name_pattern: '*.twig'
    form_themes:
        - "bootstrap_5_layout.html.twig"
        - "form/toggle_password.html.twig"
    globals:
        companyRepository: '@App\Repository\CompanyRepository'
        appName: "NUMEO"

when@test:
    twig:
        strict_variables: true
