name: Symfony Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      APP_ENV: test
      MAILER_DSN: 'null://null'
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/app_test?serverVersion=8.4"

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
        with:
          php-version: '8.4'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-publish

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - name: Install importmap assets
        run: php bin/console importmap:install --env=test

      - name: Lint container
        run: php bin/console lint:container --env=test

      - name: Lint YAML
        run: php bin/console lint:yaml config

      - name: Lint Twig
        run: php bin/console lint:twig templates --env=test

      - name: Run PHPUnit
        run: php bin/phpunit
